In [ ]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns
import plotly.express as px

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
%cd /content/drive/MyDrive/Colab

/content/drive/MyDrive/Colab


In [ ]:
df = pd.read_csv("winequality-red.csv")

In [ ]:
df.shape

(1599, 12)

In [ ]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [ ]:
df.columns = ['DoChua','AxBayHoi','AxCitric', 'Duong', 'Clo', 'SO2', 'SumSO2', 'TiTrong', 'pH', 'SO4', 'Ruou', 'DiemCL']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   DoChua    1599 non-null   float64
 1   AxBayHoi  1599 non-null   float64
 2   AxCitric  1599 non-null   float64
 3   Duong     1599 non-null   float64
 4   Clo       1599 non-null   float64
 5   SO2       1599 non-null   float64
 6   SumSO2    1599 non-null   float64
 7   TiTrong   1599 non-null   float64
 8   pH        1599 non-null   float64
 9   SO4       1599 non-null   float64
 10  Ruou      1599 non-null   float64
 11  DiemCL    1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [ ]:
df.head(10)

DoChua  AxBayHoi  AxCitric  Duong    Clo   SO2  SumSO2  TiTrong    pH  \
0     7.4      0.70      0.00    1.9  0.076  11.0    34.0   0.9978  3.51   
1     7.8      0.88      0.00    2.6  0.098  25.0    67.0   0.9968  3.20   
2     7.8      0.76      0.04    2.3  0.092  15.0    54.0   0.9970  3.26   
3    11.2      0.28      0.56    1.9  0.075  17.0    60.0   0.9980  3.16   
4     7.4      0.70      0.00    1.9  0.076  11.0    34.0   0.9978  3.51   
5     7.4      0.66      0.00    1.8  0.075  13.0    40.0   0.9978  3.51   
6     7.9      0.60      0.06    1.6  0.069  15.0    59.0   0.9964  3.30   
7     7.3      0.65      0.00    1.2  0.065  15.0    21.0   0.9946  3.39   
8     7.8      0.58      0.02    2.0  0.073   9.0    18.0   0.9968  3.36   
9     7.5      0.50      0.36    6.1  0.071  17.0   102.0   0.9978  3.35   

    SO4  Ruou  DiemCL  
0  0.56   9.4       5  
1  0.68   9.8       5  
2  0.65   9.8       5  
3  0.58   9.8       6  
4  0.56   9.4       5  
5  0.56   9.4       5  
6  0.46   9.4       5  
7  0.47  10.0       7  
8  0.57   9.5       7  
9  0.80  10.5       5

In [ ]:
tmp = df.DoChua.unique()
tmp.sort()
tmp

array([ 4.6,  4.7,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,
        5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,
        6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,
        8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ,
        9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. , 10.1,
       10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. , 11.1, 11.2,
       11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1, 12.2, 12.3,
       12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.2, 13.3, 13.4, 13.5,
       13.7, 13.8, 14. , 14.3, 15. , 15.5, 15.6, 15.9])

In [ ]:
for i in range(0, len(df.DoChua)):
    if 4.6 <= df.DoChua[i] < 5.73:
        df.DoChua[i] = 0
    elif df.DoChua[i] < 6.86:
        df.DoChua[i] = 1
    elif df.DoChua[i] < 7.99:
        df.DoChua[i] = 2
    elif df.DoChua[i] < 9.12:
        df.DoChua[i] = 3
    elif df.DoChua[i] < 10.25:
        df.DoChua[i] = 4
    elif df.DoChua[i] < 11.38:
        df.DoChua[i] = 5
    elif df.DoChua[i] < 12.51:
        df.DoChua[i] = 6
    elif df.DoChua[i] < 13.64:
        df.DoChua[i] = 7
    elif df.DoChua[i] <= 15.9:
        df.DoChua[i] = 8
    df.DoChua[i] += 1

<ipython-input-82-9a9f4c6013c9>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.DoChua[i] = 2
<ipython-input-82-9a9f4c6013c9>:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.DoChua[i] += 1
<ipython-input-82-9a9f4c6013c9>:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.DoChua[i] = 5
<ipython-input-82-9a9f4c6013c9>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats

In [ ]:
tmp = df.DoChua.unique()
tmp.sort()
tmp

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
tmp = df.AxBayHoi.unique()
tmp.sort()
tmp

array([0.12 , 0.16 , 0.18 , 0.19 , 0.2  , 0.21 , 0.22 , 0.23 , 0.24 ,
       0.25 , 0.26 , 0.27 , 0.28 , 0.29 , 0.295, 0.3  , 0.305, 0.31 ,
       0.315, 0.32 , 0.33 , 0.34 , 0.35 , 0.36 , 0.365, 0.37 , 0.38 ,
       0.39 , 0.395, 0.4  , 0.41 , 0.415, 0.42 , 0.43 , 0.44 , 0.45 ,
       0.46 , 0.47 , 0.475, 0.48 , 0.49 , 0.5  , 0.51 , 0.52 , 0.53 ,
       0.54 , 0.545, 0.55 , 0.56 , 0.565, 0.57 , 0.575, 0.58 , 0.585,
       0.59 , 0.595, 0.6  , 0.605, 0.61 , 0.615, 0.62 , 0.625, 0.63 ,
       0.635, 0.64 , 0.645, 0.65 , 0.655, 0.66 , 0.665, 0.67 , 0.675,
       0.68 , 0.685, 0.69 , 0.695, 0.7  , 0.705, 0.71 , 0.715, 0.72 ,
       0.725, 0.73 , 0.735, 0.74 , 0.745, 0.75 , 0.755, 0.76 , 0.765,
       0.77 , 0.775, 0.78 , 0.785, 0.79 , 0.795, 0.8  , 0.805, 0.81 ,
       0.815, 0.82 , 0.825, 0.83 , 0.835, 0.84 , 0.845, 0.85 , 0.855,
       0.86 , 0.865, 0.87 , 0.875, 0.88 , 0.885, 0.89 , 0.895, 0.9  ,
       0.91 , 0.915, 0.92 , 0.935, 0.95 , 0.955, 0.96 , 0.965, 0.975,
       0.98 , 1.   ,

In [ ]:
for i in range(0, len(df.AxBayHoi)):
    if 0.12 <= df.AxBayHoi[i] < 0.27:
        df.AxBayHoi[i]  = 0
    elif df.AxBayHoi[i] < 0.41:
        df.AxBayHoi[i] = 1
    elif df.AxBayHoi[i] < 0.56:
        df.AxBayHoi[i] = 2
    elif df.AxBayHoi[i] < 0.7:
        df.AxBayHoi[i] = 3
    elif df.AxBayHoi[i] < 0.85:
        df.AxBayHoi[i] = 4
    elif df.AxBayHoi[i] < 1.0:
        df.AxBayHoi[i] = 5
    elif df.AxBayHoi[i] < 1.14:
        df.AxBayHoi[i] = 6
    elif df.AxBayHoi[i] <= 1.58:
        df.AxBayHoi[i] = 7
    df.AxBayHoi[i] += 1

<ipython-input-85-5bbc54263ddc>:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.AxBayHoi[i] = 4
<ipython-input-85-5bbc54263ddc>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.AxBayHoi[i] += 1
<ipython-input-85-5bbc54263ddc>:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.AxBayHoi[i] = 5
<ipython-input-85-5bbc54263ddc>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the 

In [ ]:
tmp = df.AxBayHoi.unique()
tmp.sort()
tmp

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
tmp = df.AxCitric.unique()
tmp.sort()
tmp

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.78, 0.79, 1.  ])

In [ ]:
for i in range(0, len(df.AxCitric)):
    if 0 <= df.AxCitric[i] < 0.1:
        df.AxCitric[i]  = 0
    elif df.AxCitric[i] < 0.2:
        df.AxCitric[i] = 1
    elif df.AxCitric[i] < 0.3:
        df.AxCitric[i] = 2
    elif df.AxCitric[i] < 0.4:
        df.AxCitric[i] = 3
    elif df.AxCitric[i] < 0.5:
        df.AxCitric[i] = 4
    elif df.AxCitric[i] < 0.6:
        df.AxCitric[i] = 5
    elif df.AxCitric[i] < 0.7:
        df.AxCitric[i] = 6
    elif df.AxCitric[i] < 0.8:
        df.AxCitric[i] = 7
    elif df.AxCitric[i] <= 1:
        df.AxCitric[i] = 8
    df.AxCitric[i] += 1

<ipython-input-88-0fa2b35facc0>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.AxCitric[i]  = 0
<ipython-input-88-0fa2b35facc0>:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.AxCitric[i] += 1
<ipython-input-88-0fa2b35facc0>:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.AxCitric[i] = 5
<ipython-input-88-0fa2b35facc0>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the 

In [ ]:
tmp = df.AxCitric.unique()
tmp.sort()
tmp

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
tmp = df.Duong.unique()
tmp.sort()
tmp

array([ 0.9 ,  1.2 ,  1.3 ,  1.4 ,  1.5 ,  1.6 ,  1.65,  1.7 ,  1.75,
        1.8 ,  1.9 ,  2.  ,  2.05,  2.1 ,  2.15,  2.2 ,  2.25,  2.3 ,
        2.35,  2.4 ,  2.5 ,  2.55,  2.6 ,  2.65,  2.7 ,  2.8 ,  2.85,
        2.9 ,  2.95,  3.  ,  3.1 ,  3.2 ,  3.3 ,  3.4 ,  3.45,  3.5 ,
        3.6 ,  3.65,  3.7 ,  3.75,  3.8 ,  3.9 ,  4.  ,  4.1 ,  4.2 ,
        4.25,  4.3 ,  4.4 ,  4.5 ,  4.6 ,  4.65,  4.7 ,  4.8 ,  5.  ,
        5.1 ,  5.15,  5.2 ,  5.4 ,  5.5 ,  5.6 ,  5.7 ,  5.8 ,  5.9 ,
        6.  ,  6.1 ,  6.2 ,  6.3 ,  6.4 ,  6.55,  6.6 ,  6.7 ,  7.  ,
        7.2 ,  7.3 ,  7.5 ,  7.8 ,  7.9 ,  8.1 ,  8.3 ,  8.6 ,  8.8 ,
        8.9 ,  9.  , 10.7 , 11.  , 12.9 , 13.4 , 13.8 , 13.9 , 15.4 ,
       15.5 ])

In [ ]:
for i in range(0, len(df.Duong)):
    if 0.9 <= df.Duong[i] < 2.36:
        df.Duong[i]  = 0
    elif df.Duong[i] < 3.82:
        df.Duong[i] = 1
    elif df.Duong[i] < 5.28:
        df.Duong[i] = 2
    elif df.Duong[i] < 6.74:
        df.Duong[i] = 3
    elif df.Duong[i] < 8.99:
        df.Duong[i] = 4
    elif df.Duong[i] <= 15.5:
        df.Duong[i] = 5
    df.Duong[i] += 1

<ipython-input-91-2d1d8ce179b1>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Duong[i]  = 0
<ipython-input-91-2d1d8ce179b1>:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Duong[i] += 1
<ipython-input-91-2d1d8ce179b1>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Duong[i] = 1
<ipython-input-91-2d1d8ce179b1>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in

In [ ]:
tmp = df.Duong.unique()
tmp.sort()
tmp

array([1., 2., 3., 4., 5., 6.])

In [ ]:
tmp = df.Clo.unique()
tmp.sort()
tmp

array([0.012, 0.034, 0.038, 0.039, 0.041, 0.042, 0.043, 0.044, 0.045,
       0.046, 0.047, 0.048, 0.049, 0.05 , 0.051, 0.052, 0.053, 0.054,
       0.055, 0.056, 0.057, 0.058, 0.059, 0.06 , 0.061, 0.062, 0.063,
       0.064, 0.065, 0.066, 0.067, 0.068, 0.069, 0.07 , 0.071, 0.072,
       0.073, 0.074, 0.075, 0.076, 0.077, 0.078, 0.079, 0.08 , 0.081,
       0.082, 0.083, 0.084, 0.085, 0.086, 0.087, 0.088, 0.089, 0.09 ,
       0.091, 0.092, 0.093, 0.094, 0.095, 0.096, 0.097, 0.098, 0.099,
       0.1  , 0.101, 0.102, 0.103, 0.104, 0.105, 0.106, 0.107, 0.108,
       0.109, 0.11 , 0.111, 0.112, 0.113, 0.114, 0.115, 0.116, 0.117,
       0.118, 0.119, 0.12 , 0.121, 0.122, 0.123, 0.124, 0.125, 0.126,
       0.127, 0.128, 0.132, 0.136, 0.137, 0.143, 0.145, 0.146, 0.147,
       0.148, 0.152, 0.153, 0.157, 0.159, 0.161, 0.165, 0.166, 0.168,
       0.169, 0.17 , 0.171, 0.172, 0.174, 0.176, 0.178, 0.186, 0.19 ,
       0.194, 0.2  , 0.205, 0.213, 0.214, 0.216, 0.222, 0.226, 0.23 ,
       0.235, 0.236,

In [ ]:
for i in range(0, len(df.Clo)):
    if 0.01 < df.Clo[i] < 0.07:
        df.Clo[i] = 0
    elif df.Clo[i] < 0.13:
        df.Clo[i] = 1
    elif df.Clo[i] < 0.19:
        df.Clo[i] = 2
    elif df.Clo[i] < 0.27:
        df.Clo[i] = 3
    elif df.Clo[i] <= 0.611:
        df.Clo[i] = 4
    df.Clo[i] += 1

<ipython-input-94-96469ea1bdd2>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Clo[i] = 1
<ipython-input-94-96469ea1bdd2>:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Clo[i] += 1
<ipython-input-94-96469ea1bdd2>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Clo[i] = 0
<ipython-input-94-96469ea1bdd2>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the do

In [ ]:
tmp = df.Clo.unique()
tmp.sort()
tmp

array([1., 2., 3., 4., 5.])

In [ ]:
tmp = df.SO2.unique()
tmp.sort()
tmp

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  5.5,  6. ,  7. ,  8. ,  9. , 10. ,
       11. , 12. , 13. , 14. , 15. , 16. , 17. , 18. , 19. , 20. , 21. ,
       22. , 23. , 24. , 25. , 26. , 27. , 28. , 29. , 30. , 31. , 32. ,
       33. , 34. , 35. , 36. , 37. , 37.5, 38. , 39. , 40. , 40.5, 41. ,
       42. , 43. , 45. , 46. , 47. , 48. , 50. , 51. , 52. , 53. , 54. ,
       55. , 57. , 66. , 68. , 72. ])

In [ ]:
for i in range(0, len(df.SO2)):
    if 1 <= df.SO2[i] < 8.1:
        df.SO2[i]  = 0
    elif df.SO2[i] < 15.2:
        df.SO2[i] = 1
    elif df.SO2[i] < 22.3:
        df.SO2[i] = 2
    elif df.SO2[i] < 29.4:
        df.SO2[i] = 3
    elif df.SO2[i] < 36.5:
        df.SO2[i] = 4
    elif df.SO2[i] < 43.6:
        df.SO2[i] = 5
    elif df.SO2[i] < 50.7:
        df.SO2[i] = 6
    elif df.SO2[i] < 57.8:
        df.SO2[i] = 7
    elif df.SO2[i] <= 72:
        df.SO2[i] = 8
    df.SO2[i] += 1

<ipython-input-97-199b241eb360>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.SO2[i] = 1
<ipython-input-97-199b241eb360>:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.SO2[i] += 1
<ipython-input-97-199b241eb360>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.SO2[i] = 3
<ipython-input-97-199b241eb360>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the do

In [ ]:
tmp = df.SO2.unique()
tmp.sort()
tmp

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
tmp = df.SumSO2.unique()
tmp.sort()
tmp

array([  6. ,   7. ,   8. ,   9. ,  10. ,  11. ,  12. ,  13. ,  14. ,
        15. ,  16. ,  17. ,  18. ,  19. ,  20. ,  21. ,  22. ,  23. ,
        24. ,  25. ,  26. ,  27. ,  28. ,  29. ,  30. ,  31. ,  32. ,
        33. ,  34. ,  35. ,  36. ,  37. ,  38. ,  39. ,  40. ,  41. ,
        42. ,  43. ,  44. ,  45. ,  46. ,  47. ,  48. ,  49. ,  50. ,
        51. ,  52. ,  53. ,  54. ,  55. ,  56. ,  57. ,  58. ,  59. ,
        60. ,  61. ,  62. ,  63. ,  64. ,  65. ,  66. ,  67. ,  68. ,
        69. ,  70. ,  71. ,  72. ,  73. ,  74. ,  75. ,  76. ,  77. ,
        77.5,  78. ,  79. ,  80. ,  81. ,  82. ,  83. ,  84. ,  85. ,
        86. ,  87. ,  88. ,  89. ,  90. ,  91. ,  92. ,  93. ,  94. ,
        95. ,  96. ,  98. ,  99. , 100. , 101. , 102. , 103. , 104. ,
       105. , 106. , 108. , 109. , 110. , 111. , 112. , 113. , 114. ,
       115. , 116. , 119. , 120. , 121. , 122. , 124. , 125. , 126. ,
       127. , 128. , 129. , 130. , 131. , 133. , 134. , 135. , 136. ,
       139. , 140. ,

In [ ]:
for i in range(0, len(df.SumSO2)):
    if 6 <= df.SumSO2[i] < 34.3:
        df.SumSO2[i]  = 0
    elif df.SumSO2[i] < 62.6:
        df.SumSO2[i] = 1
    elif df.SumSO2[i] < 90.9:
        df.SumSO2[i] = 2
    elif df.SumSO2[i] < 119.2:
        df.SumSO2[i] = 3
    elif df.SumSO2[i] < 147.5:
        df.SumSO2[i] = 4
    elif df.SumSO2[i] <= 289:
        df.SumSO2[i] = 5
    df.SumSO2[i] += 1

<ipython-input-100-cb5da40f9037>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.SumSO2[i]  = 0
<ipython-input-100-cb5da40f9037>:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.SumSO2[i] += 1
<ipython-input-100-cb5da40f9037>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.SumSO2[i] = 2
<ipython-input-100-cb5da40f9037>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the cav

In [ ]:
tmp = df.SumSO2.unique()
tmp.sort()
tmp

array([1., 2., 3., 4., 5., 6.])

In [ ]:
tmp = df.TiTrong.unique()
tmp.sort()
tmp

array([0.99007, 0.9902 , 0.99064, 0.9908 , 0.99084, 0.9912 , 0.9915 ,
       0.99154, 0.99157, 0.9916 , 0.99162, 0.9917 , 0.99182, 0.99191,
       0.9921 , 0.9922 , 0.99235, 0.99236, 0.9924 , 0.99242, 0.99252,
       0.99256, 0.99258, 0.99264, 0.9927 , 0.9928 , 0.99286, 0.9929 ,
       0.99292, 0.99294, 0.99306, 0.99314, 0.99316, 0.99318, 0.9932 ,
       0.99322, 0.99323, 0.99328, 0.9933 , 0.99331, 0.99332, 0.99334,
       0.99336, 0.9934 , 0.99341, 0.99344, 0.99346, 0.99348, 0.9935 ,
       0.99352, 0.99354, 0.99356, 0.99357, 0.99358, 0.9936 , 0.99362,
       0.99364, 0.9937 , 0.99371, 0.99374, 0.99376, 0.99378, 0.99379,
       0.9938 , 0.99384, 0.99385, 0.99386, 0.99387, 0.99388, 0.99392,
       0.99394, 0.99395, 0.99396, 0.99397, 0.994  , 0.99402, 0.99408,
       0.9941 , 0.99414, 0.99416, 0.99417, 0.99418, 0.99419, 0.9942 ,
       0.99425, 0.99426, 0.99428, 0.9943 , 0.99434, 0.99437, 0.99438,
       0.99439, 0.9944 , 0.99444, 0.99448, 0.99451, 0.99454, 0.99456,
       0.99458, 0.99

In [ ]:
for i in range(0, len(df.TiTrong)):
    if 0.99 < df.TiTrong[i] < 0.994:
        df.TiTrong[i]  = 0
    elif df.TiTrong[i] < 0.995:
        df.TiTrong[i] = 1
    elif df.TiTrong[i] < 0.996:
        df.TiTrong[i] = 2
    elif df.TiTrong[i] < 0.997:
        df.TiTrong[i] = 3
    elif df.TiTrong[i] < 0.998:
        df.TiTrong[i] = 4
    elif df.TiTrong[i] < 0.999:
        df.TiTrong[i] = 5
    elif df.TiTrong[i] < 1:
        df.TiTrong[i] = 6
    elif df.TiTrong[i] < 1.0002:
        df.TiTrong[i] = 7
    elif df.TiTrong[i] < 1.0006:
        df.TiTrong[i] = 8
    elif df.TiTrong[i] < 1.001:
        df.TiTrong[i] = 9
    elif df.TiTrong[i] < 1.0021:
        df.TiTrong[i] = 10
    elif df.TiTrong[i] < 1.004:
        df.TiTrong[i] = 11
    df.TiTrong[i] += 1

<ipython-input-103-36c35f5d8856>:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.TiTrong[i] = 4
<ipython-input-103-36c35f5d8856>:26: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.TiTrong[i] += 1
<ipython-input-103-36c35f5d8856>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.TiTrong[i] = 3
<ipython-input-103-36c35f5d8856>:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the

In [ ]:
tmp = df.pH.unique()
tmp.sort()
tmp

array([2.74, 2.86, 2.87, 2.88, 2.89, 2.9 , 2.92, 2.93, 2.94, 2.95, 2.98,
       2.99, 3.  , 3.01, 3.02, 3.03, 3.04, 3.05, 3.06, 3.07, 3.08, 3.09,
       3.1 , 3.11, 3.12, 3.13, 3.14, 3.15, 3.16, 3.17, 3.18, 3.19, 3.2 ,
       3.21, 3.22, 3.23, 3.24, 3.25, 3.26, 3.27, 3.28, 3.29, 3.3 , 3.31,
       3.32, 3.33, 3.34, 3.35, 3.36, 3.37, 3.38, 3.39, 3.4 , 3.41, 3.42,
       3.43, 3.44, 3.45, 3.46, 3.47, 3.48, 3.49, 3.5 , 3.51, 3.52, 3.53,
       3.54, 3.55, 3.56, 3.57, 3.58, 3.59, 3.6 , 3.61, 3.62, 3.63, 3.66,
       3.67, 3.68, 3.69, 3.7 , 3.71, 3.72, 3.74, 3.75, 3.78, 3.85, 3.9 ,
       4.01])

In [ ]:
for i in range(0, len(df.pH)):
    if 2.74 <= df.pH[i] < 2.87:
        df.pH[i] = 0
    elif df.pH[i] < 2.99:
        df.pH[i] = 1
    elif df.pH[i] < 3.12:
        df.pH[i] = 2
    elif df.pH[i] < 3.25:
        df.pH[i] = 3
    elif df.pH[i] < 3.38:
        df.pH[i] = 4
    elif df.pH[i] < 3.50:
        df.pH[i] = 5
    elif df.pH[i] < 3.63:
        df.pH[i] = 6
    elif df.pH[i] < 3.76:
       df.pH[i] = 7
    elif df.pH[i] <= 4.01:
        df.pH[i] = 8
    df.pH[i] += 1

In [ ]:
tmp = df.SO4.unique()
tmp.sort()
tmp

array([0.33, 0.37, 0.39, 0.4 , 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48,
       0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59,
       0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ,
       0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 , 0.81,
       0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 , 0.91, 0.92,
       0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  , 1.01, 1.02, 1.03,
       1.04, 1.05, 1.06, 1.07, 1.08, 1.09, 1.1 , 1.11, 1.12, 1.13, 1.14,
       1.15, 1.16, 1.17, 1.18, 1.2 , 1.22, 1.26, 1.28, 1.31, 1.33, 1.34,
       1.36, 1.56, 1.59, 1.61, 1.62, 1.95, 1.98, 2.  ])

In [ ]:
for i in range(0, len(df.SO4)):
    if 0.33 <= df.SO4[i] < 0.5:
        df.SO4[i] = 0
    elif df.SO4[i] < 0.66:
        df.SO4[i] = 1
    elif df.SO4[i] < 0.83:
        df.SO4[i] = 2
    elif df.SO4[i] < 1:
        df.SO4[i] = 3
    elif df.SO4[i] < 1.17:
        df.SO4[i] = 4
    elif df.SO4[i] < 1.35:
        df.SO4[i] = 5
    elif df.SO4[i] <= 2:
        df.SO4[i] = 6
    df.SO4[i] += 1

In [ ]:
tmp = df.Ruou.unique()
tmp.sort()
tmp

array([ 8.4       ,  8.5       ,  8.7       ,  8.8       ,  9.        ,
        9.05      ,  9.1       ,  9.2       ,  9.23333333,  9.25      ,
        9.3       ,  9.4       ,  9.5       ,  9.55      ,  9.56666667,
        9.6       ,  9.7       ,  9.8       ,  9.9       ,  9.95      ,
       10.        , 10.03333333, 10.1       , 10.2       , 10.3       ,
       10.4       , 10.5       , 10.55      , 10.6       , 10.7       ,
       10.75      , 10.8       , 10.9       , 11.        , 11.06666667,
       11.1       , 11.2       , 11.3       , 11.4       , 11.5       ,
       11.6       , 11.7       , 11.8       , 11.9       , 11.95      ,
       12.        , 12.1       , 12.2       , 12.3       , 12.4       ,
       12.5       , 12.6       , 12.7       , 12.8       , 12.9       ,
       13.        , 13.1       , 13.2       , 13.3       , 13.4       ,
       13.5       , 13.56666667, 13.6       , 14.        , 14.9       ])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   DoChua    1599 non-null   float64
 1   AxBayHoi  1599 non-null   float64
 2   AxCitric  1599 non-null   float64
 3   Duong     1599 non-null   float64
 4   Clo       1599 non-null   float64
 5   SO2       1599 non-null   float64
 6   SumSO2    1599 non-null   float64
 7   TiTrong   1599 non-null   float64
 8   pH        1599 non-null   float64
 9   SO4       1599 non-null   float64
 10  Ruou      1599 non-null   float64
 11  DiemCL    1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [ ]:
df['goodquality'] = [1 if x >= 7 else 0 for x in df['DiemCL']]

In [ ]:
df.head(20)

DoChua  AxBayHoi  AxCitric  Duong  Clo  SO2  SumSO2  TiTrong   pH  SO4  \
0      3.0       5.0       1.0    1.0  2.0  2.0     1.0      5.0  7.0  2.0   
1      3.0       6.0       1.0    2.0  2.0  4.0     3.0      4.0  4.0  3.0   
2      3.0       5.0       1.0    1.0  2.0  2.0     2.0      5.0  5.0  2.0   
3      6.0       2.0       6.0    1.0  2.0  3.0     2.0      6.0  4.0  2.0   
4      3.0       5.0       1.0    1.0  2.0  2.0     1.0      5.0  7.0  2.0   
5      3.0       4.0       1.0    1.0  2.0  2.0     2.0      5.0  7.0  2.0   
6      3.0       4.0       1.0    1.0  1.0  2.0     2.0      4.0  5.0  1.0   
7      3.0       4.0       1.0    1.0  1.0  2.0     1.0      2.0  6.0  1.0   
8      3.0       4.0       1.0    1.0  2.0  2.0     1.0      4.0  5.0  2.0   
9      3.0       3.0       4.0    4.0  2.0  3.0     4.0      5.0  5.0  3.0   
10     2.0       4.0       1.0    1.0  2.0  2.0     3.0      3.0  5.0  2.0   
11     3.0       3.0       4.0    4.0  2.0  3.0     4.0      5.0  5.0  3.0   
12     1.0       4.0       1.0    1.0  2.0  3.0     2.0      2.0  7.0  2.0   
13     3.0       4.0       3.0    1.0  2.0  2.0     1.0      5.0  5.0  7.0   
14     4.0       4.0       2.0    2.0  3.0  8.0     5.0      6.0  4.0  4.0   
15     4.0       4.0       2.0    3.0  3.0  8.0     6.0      6.0  4.0  4.0   
16     4.0       2.0       6.0    1.0  2.0  5.0     4.0      4.0  5.0  3.0   
17     4.0       4.0       3.0    1.0  5.0  3.0     2.0      4.0  3.0  6.0   
18     3.0       4.0       1.0    3.0  2.0  1.0     1.0      5.0  6.0  2.0   
19     3.0       2.0       6.0    1.0  5.0  3.0     2.0      4.0  3.0  5.0   

    Ruou  DiemCL  goodquality  
0    9.4       5            0  
1    9.8       5            0  
2    9.8       5            0  
3    9.8       6            0  
4    9.4       5            0  
5    9.4       5            0  
6    9.4       5            0  
7   10.0       7            1  
8    9.5       7            1  
9   10.5       5            0  
10   9.2       5            0  
11  10.5       5            0  
12   9.9       5            0  
13   9.1       5            0  
14   9.2       5            0  
15   9.2       5            0  
16  10.5       7            1  
17   9.3       5            0  
18   9.0       4            0  
19   9.2       6            0

In [ ]:
cor = df.corr()

In [ ]:
cotdt = ['DoChua','AxBayHoi','AxCitric', 'Duong', 'Clo', 'SO2', 'SumSO2', 'TiTrong', 'pH', 'SO4']
print(type(cotdt))

<class 'list'>


In [ ]:
x = df[cotdt]
y = df['goodquality'].astype('float')

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.5, random_state = 26)

clf = DecisionTreeClassifier(criterion='entropy', max_depth=5)
clf = clf.fit(X_train, y_train)

predictions = clf.predict(X_test) 

In [ ]:
test1 = [['7.5', '3.0',	'4.0', '4.0',	'2.0', '3.0', '4.0', '5.0',	'5.0', '3.0']]
prediction = clf.predict(test1)
print(prediction)
for item in prediction:
  if item == 0.0 :
    item = 'Ruou chat luong tot'
  else:
    item = 'Ruou chat luong khong tot'
  print(item)

[0.]
Ruou chat luong tot


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [ ]:
import numpy as np  
from sklearn.model_selection import train_test_split  
from sklearn.svm import SVC  

In [ ]:
svc = SVC()  
svc.fit(X_train, y_train)  

SVC()

In [ ]:
def compute_accuracy(Y_true, Y_pred):  
    correctly_predicted = 0  
    # lặp lại nhãn và kiểm tra độ trính xác  
    for true_label, predicted in zip(Y_true, Y_pred):  
        if true_label == predicted:  
            correctly_predicted += 1  
    # Tính toán điểm chính xác của việc so sánh   
    accuracy_score = correctly_predicted / len(Y_true)  
    return accuracy_score  

In [ ]:
Y_pred = svc.predict(X_test)   
score = compute_accuracy(y_test, Y_pred)  
print(score)

0.87375


In [ ]:
def compute_accuracy(Y_true, Y_pred): 
    correctly_predicted = 0  
    # lặp lại nhãn và kiểm tra độ trính xác  
    for true_label, predicted in zip(Y_true, Y_pred):  
        if true_label == predicted:  
            correctly_predicted += 1  
            print(true_label, ", ", predicted)
    # Tính toán điểm chính xác của việc so sánh   
    accuracy_score = correctly_predicted / len(Y_true)  
    return accuracy_score

In [ ]:
Y_pred = svc.predict(X_test)   
score = compute_accuracy(y_test, Y_pred)  
print(score)

0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
1.0 ,  1.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0
0.0 ,  0.0